import StyledComponentsRegistry from '@/lib/SSRStyledComponents';
import type { Metadata } from 'next';
import { Providers } from './provider';
import { GlobalStyles } from '@/styles/global';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ru">
			<body>
				<Providers>
					<StyledComponentsRegistry>
						<GlobalStyles />
						{children}
					</StyledComponentsRegistry>
				</Providers>
			</body>
		</html>
	);
}
